### ISSUE TITLE
@arcgis/core/assets/esri/themes

### ISSUE THREAD

**Issue by julkuh** [Esri/jsapi-resources#312]
I am reporting an issue with 

- [ ] TypeScript definitions
- [x] another resource in this repository

The File @arcgis/core/assets/esri/themes/base/widgets/_Widget.scss contains a CSS selector that is too unspecific and may target unwanted Elements. 

The selector "[class*=esri-icon]" matches as soon as any given class contains "esri-icon". This may lead to severe problems in combination with setting those elements to display:inline-block accidentally.

A much safer approach would be to use the starts-with selector "[class^=esri-icon]" (as in many other cases with esri-icon).
Therefore, the following section inside _Widget.scss 

``` css
[class*="esri-icon"] {
    font-size: $icon-size;
    display: inline-block;
}
```
should be replaced by

``` css
[class^="esri-icon"] {
    font-size: $icon-size;
    display: inline-block;
}
```
See also my Pull-Request over at [arcgis-js-api](https://github.com/Esri/arcgis-js-api/pull/16)

Thanks a lot :)
Julian
